### ISSUE TITLE
Program Won't Launch

### ISSUE THREAD

**Issue by ghost** [SchildiChat/schildichat-desktop#115]
Worked fine yesterday, I think there was an update so that might be why. When I try to launch SchildiChat in Debian 10, I get the following error in the terminal: 

```
Seshat unexpected error: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.8G4KpM)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/SchildiChat/resources/app.asar/node_modules/matrix-seshat/lib/index.js:16:22)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
Segmentation fault
```

Based on some quick searching, this seems to be an issue with GLIBC that presented in Element (formerly Riot) last year. I tried a reinstall but no dice. Is there a way to roll back versions? Thanks.

**Comment by Kloenk** [comment]
Yes, the problem is that the GLIBC is too old on your system. I think from a security standpoint the only option is to upgrade your glibc (Debian should have some unstable channels with saner versions), or to rebuild SchildiChat from source with a different electron version.

**Comment by natebartram** [comment]
Bummer. I'll see about switching over to the latest repos then. I remember looking into it, it didn't look too hard but given my skill level I would definitely need some time to sit down and focus on it. Thanks!

**Comment by su-ex** [comment]
I build for Debian stable, which is now Debian 11 (bullseye). So upgrading your repos is probably your best choice anyway.

**Comment by natebartram** [comment]
> I build for Debian stable, which is now Debian 11 (bullseye). So upgrading your repos is probably your best choice anyway.

Yeah, I use Qubes and turns out I missed the memo that Debian 11 was now available for me. I'll try upgrading today and let you know if that fixes it. Thanks.

**Comment by su-ex** [comment]
@natebartram Could you solve this by updating?
