### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by wuast94** [SchildiChat/schildichat-desktop#229]
i get MaxListenersExceededWarning error:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 call listeners added. Use emitter.setMaxListeners() to increase limit
    at d (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1579)
    at s.addListener (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:4163)
    at V.componentDidMount (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/init.js:1:1317137)
    at _s (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1733870)
    at Nl (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1750676)
    at t.unstable_runWithPriority (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1775892)
    at Vi (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1692816)
    at Ol (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1747415)
    at El (https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1743526)
    at https://sub.domain.tld/bundles/713b08846cdbdfa5cd1c/vendors~init.js:2:1693039
```
    
  dont know if its related but on my sidebar not all profile pictures are loading, if i click on a chat i see them.

**Comment by wuast94** [comment]
not stale
