### ISSUE TITLE
Error in sliding Sync mode in Desktop Debian .deb

### ISSUE THREAD

**Issue by aibosss** [SchildiChat/schildichat-desktop#244]
(node:2902568) UnhandledPromiseRejectionWarning: TypeError: Unable to get a database connection Sqlite pool error: timed out waiting for connection
    at node:internal/util:375:7
    at new Promise (<anonymous>)
    at matrix_seshat::Seshat::is_room_indexed (node:internal/util:361:12)
    at Seshat.isRoomIndexed (/opt/SchildiChat/resources/app.asar/node_modules/matrix-seshat/index.js:467:16)
    at IpcMainImpl.<anonymous> (/opt/SchildiChat/resources/app.asar/lib/seshat.js:175:44)
    at Generator.next (<anonymous>)
    at /opt/SchildiChat/resources/app.asar/lib/seshat.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/SchildiChat/resources/app.asar/lib/seshat.js:19:12)
    at IpcMainImpl.<anonymous> (/opt/SchildiChat/resources/app.asar/lib/seshat.js:86:12)
(node:2902568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)

anyone else getting that?

**Comment by SpiritCroc** [comment]
Given that we're quite behind on Element upstream merges, and sliding sync is in active development (i.e., not to be considered stable at the moment), I wouldn't recommend opting in for sliding sync at the time being.

**Comment by su-ex** [comment]
Out of scope for schildi.
